
# REUSE GUIDE
# to reuse this workflow file in another project
# 1. make sure self hosted runner using the latest secrets
#   its located in ~/actions/actions.secrets
# 2. update these ENVs:
#   - PROJECT_GROUP
#   - PROJECT_NAME
#   - BUILD_CONTEXT -> for nested directory use `{{defaultContext}}:<directory>`

name: test pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:

      -
        name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:base"
          push: false
          tags: base-image
          outputs: type=docker,dest=/tmp/base-image.tar

      - 
        name: check docker image 1
        run: |
            docker images
            docker load --input /tmp/base-image.tar
            docker images
      - 
        name: check docker image 2
        run: |
            docker images
      -
        name: Build overlay image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:overlay"
          push: false
          tags: overlay-image:1.0

          # push: true
          # tags: ${{env.REGISTRY_URL}}/${{env.PROJECT_NAME}}-base-image:${{env.IMAGE_VERSION}}
          # # registry.sdlc.lacak.io/vo-api-base-image
